### ISSUE TITLE
crash when loading savegame

### ISSUE THREAD

**Issue by masher42** [KozGit/DOOM-3-BFG-VR#103]
Hi. Really great work you have done here. I love the new features. However, i am experiencing crashes while trying to load certain savegames. Sometimes it goes just fine, but every second or third time i save my game, i can't load it anymore. This happens with the 'vanilla' version of your mod without anything else added.

I just deleted the savegames folder and freshly installed the mod. Then started a new game. Then I saved the game and immediately loaded again and it worked. I proceeded with the game until i came to the first elevator. Then i saved the game again and tried to load it, but it crashed. So, if you just save and load the game a few times you should be able to reproduce this hopefully. This does also happen with autosaves.

Again. Thank you for this awesome mod !

**Comment by BernieBI** [comment]
I am having the exact same issue. the first autosave loads just fine, but any saves beyond that makes the game crash

**Comment by Andenlol** [comment]
I got the same exact problem.

**Comment by tkapis** [comment]
I saved at the top of the stairs by the exit of Mars Underground and after the marine talking to me I saved again. The 1st save still works but when loading the 2nd one, the game crashes. In fact any save from then on crashes if I try to load it.

**Comment by josefmd** [comment]
Make that another.....I get the crashing every time I try to load a save game.  I thought it was from the high res texture pack, but did a full re install using the installer without the texture pack and it is still happening.   I was having the same issue with a old install of "OculusNativeAlpha015"

**Comment by CarlKenner** [comment]
I have the same issue without the texture pack. So it's the normal behaviour.

If you lose your progress because of this bug, then you can use the DEV menu to start from a specific level, but you lose your weapons and PDAs (and difficulty setting).

**Comment by CarlKenner** [comment]
This issue is fixed in the next version.

**Comment by masher42** [comment]
I was impatient and applied pullrequest #110 and compiled it myself. While the game doesn't crash anymore when loading a savegame, it now doesn't find the savegame that has just been saved. It just prints something like "can't find savegame *****" in the console. After restarting the game, it loads the said savegame as if nothing ever happened. Sorry if this is only because i screwed something up when compiling, but i think there is still something wrong with loading savegames.

**Comment by CarlKenner** [comment]
Yes, I fixed that bug. Pull it again. I was passing the wrong thing to the console command because I tried to initialise a member variable that had the same name as the parameter. But only when loading from the PDA, not when loading from the main menu.

**Comment by masher42** [comment]
I just tried 'Doom3BFGVR_Fully_Possessed_Alpha021.zip' from your pull request. I still have the same problem. I can't load my saves before I exit the game and restart it. When the game refuses to load a savegame, it is greyed out in the load menu. It doesn't matter where I try to load it from (ingame or mainmenu). It seems that after saving, the game expects the file to be somewhere else when trying to load it.

**Comment by tkapis** [comment]
I have the same problem with loading saves as masher42.

**Comment by CarlKenner** [comment]
Grey in the menu means it thinks the save is in the "%UserProfile%\Saved Games\id Software\RBDOOM 3 BFG\base\savegame" folder, (or the save is version 1400 or below which won't be the case for games you just saved or games saved by most versions).

Try using the console command: testSavegameEnumerate after saving or before accessing the load menu.

If that doesn't work, the workaround is to exit and restart or (not recommeneded) to copy the saved game into that folder.

**Comment by masher42** [comment]
Ahh great, that did it. I hacked `testSaveGameEnumerate` into the console right after starting the game and before loading. I can save and load normally afterwards. Thanks a lot !

**Comment by tkapis** [comment]
@masher42, you say that you only have to input it 1 time.

If I make a save, I can't access it until I do the input in the console and that's for every save.

**Comment by KozGit** [comment]
With the newest changes, I am unable to load any savegames,  ( even after clean save/restart)  on a clean install, has anyone else tried with the latest commits?

**Comment by masher42** [comment]
@tkapis, yes i have to input it once per session and can load and save like i want afterwards (0.021 Alpha). I did not test with the latest commits yet. Will do and report if i find the time.

**Comment by CarlKenner** [comment]
What do you mean? What happens when you try to load a savegame?
BTW, I made some more commits before I saw your message.

**Comment by KozGit** [comment]
My save games are working now, the changes corrected the issue. Should have responded sooner, sorry.
